import type { Metadata } from "next";
import { Breadcrumb, PageHero } from "@/components/inner-page";
import { RfqBanner, SectionHeading } from "@/components/site";
import { markets } from "@/data/catalog";
export const metadata:Metadata={title:"Latin America & Global Presence",description:"Anchal India's focused automotive component export presence across Latin America."};
export default function Presence(){return <><PageHero eyebrow="Latin America / Global presence" title="An India–Latin America automotive bridge." copy="Market experience shapes every decision—from application focus and assortment building to packaging, documentation and shipment planning."/><Breadcrumb current="Global Presence"/>
 <section className="section presence-hero"><div className="container presence-layout"><div className="map-visual"><div className="india-pin">INDIA</div><div className="latam-shape">LATIN<br/>AMERICA</div></div><div><SectionHeading eyebrow="Primary market focus" title="Deep regional familiarity."/><p>We work with the diversity of Latin America in mind. Vehicle populations, model names and commercial expectations differ across borders; our approach is built to identify and respond to those differences.</p></div></div></section>
 <section className="section section-light"><div className="container"><SectionHeading eyebrow="Active market knowledge" title="Markets we focus on."/><div className="country-grid">{markets.map((m,i)=><div key={m}><span>{String(i+1).padStart(2,"0")}</span><b>{m}</b></div>)}</div></div></section>
 <section className="section soft-section"><div className="container"><div className="three-grid">{[["Product relevance","Vehicle-family and high-frequency component focus based on market requirements."],["Responsive communication","English-led export support with a Spanish-ready digital architecture."],["Shipment coordination","Commercial documentation and consolidation planning from India."]].map(([t,c])=><article className="info-card" key={t}><h3>{t}</h3><p>{c}</p></article>)}</div></div></section><RfqBanner/></>}
