import Link from "next/link";
import { PageCta, SectionTitle, WorldMap } from "@/components/site";
export const metadata={title:"About Us | Anchal India"};
const milestones=[
  ["2006","THE BEGINNING","Pistons and rings for chainsaw applications."],
  ["2008","AILYN","Motorcycle spare parts and the beginning of our own-brand journey."],
  ["2014","HARKES + NEW MARKETS","HARKES begins its journey alongside deeper entry into Latin America."],
  ["2016","THE NETWORK EXPANDS","Relationships with established Indian OEM and component brands broaden our solutions."],
  ["2026","COMPLETE SOLUTIONS","Two decades of knowledge, own brands, industry relationships and international experience."],
];
export default function About(){
 return <>
  <section className="about-hero"><div className="about-film"/><div className="shell"><p>ABOUT ANCHAL INDIA</p><h1>Built in India.<br/><em>Connected by trust.</em><br/>Growing with the world.</h1><span>Since 2006, focused product knowledge has evolved into a complete automotive solutions ecosystem.</span></div></section>
  <section className="section story-chapter" id="story"><div className="shell story-grid"><div><SectionTitle kicker="OUR STORY" title="What began with parts became a pursuit of complete solutions."/><p>In 2006, Anchal India began with a focused understanding of components and a belief that Indian products could compete confidently in international markets.</p><p>What followed was an expansion of knowledge—across vehicles, applications, brands, markets and customer requirements. Today, we bring those capabilities together so customers can approach one dependable organisation with diverse automotive needs.</p></div><div className="story-values"><article><span>OUR VISION</span><strong>Build global confidence in Indian automotive capability.</strong></article><article><span>OUR MISSION</span><strong>Connect markets with dependable products, application knowledge and responsible execution.</strong></article><article><span>OUR BELIEF</span><strong>Products create business. Trust creates partnerships.</strong></article></div></div></section>
  <section className="india-pride"><div className="shell"><div className="lion-placeholder"><span>INDIA</span><b>♚</b></div><div><p>MADE IN INDIA</p><h2>Built to move the world.</h2><span>Our roots are Indian. Our outlook is global. We bring Indian automotive capability, application knowledge and trusted industry relationships to international markets.</span></div></div></section>
  <section className="section journey" id="journey"><div className="shell"><SectionTitle kicker="OUR JOURNEY" title="Twenty years in motion." copy="A focused beginning. Two own brands. A wider automotive network. A global future."/><div className="journey-road">{milestones.map(([year,title,copy],i)=><article key={year}><b>{year}</b><span>{String(i+1).padStart(2,"0")}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
  <section className="section process-section" id="process"><div className="shell"><SectionTitle center kicker="HOW WE WORK" title="From requirement to destination."/><div className="process-film">{["Understand","Identify","Build the solution","Check & consolidate","Document","Deliver globally"].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><i>{["⌕","◎","✣","▦","▤","➜"][i]}</i><b>{x}</b></div>)}</div><p className="process-promise">ONE REQUIREMENT · ONE COORDINATED SOLUTION · ONE PARTNER</p></div></section>
  <section className="section leadership" id="leadership"><div className="shell"><SectionTitle kicker="LEADERSHIP" title="Built by experience. Carried forward by ambition."/><div className="founders"><article><div className="portrait-placeholder">PHOTO</div><div><small>FOUNDER</small><h3>Mr. Shashi Bhushan</h3><p>Founder profile and personal journey will be added only from verified company material.</p></div></article><article><div className="portrait-placeholder">PHOTO</div><div><small>FOUNDER</small><h3>Mr. Ajay Kumar Tyagi</h3><p>Founder profile and personal journey will be added only from verified company material.</p></div></article></div></div></section>
  <section className="section about-global"><div className="shell global-layout"><div><SectionTitle kicker="GLOBAL PRESENCE" title="One supply network. Multiple markets." copy="India is our operating origin. Latin America is our deepest established international region, supported by market connections across Turkey, the Middle East, Egypt and the Philippines, and a sourcing contact in China."/><Link href="/global-presence" className="text-action blue">Explore the network ↗</Link></div><WorldMap/></div></section>
  <section className="section credibility" id="credentials"><div className="shell"><SectionTitle kicker="TRUST, EARNED OVER TIME" title="Proof belongs inside the story." copy="Official awards, EEPC membership, export credentials and certificates will appear here as verified visual assets are supplied."/><div className="credential-gallery">{["EEPC Membership","Export Credentials","Brand Recognition","Awards & Milestones"].map(x=><div key={x}><span>OFFICIAL ASSET</span><b>{x}</b><small>Verified image pending</small></div>)}</div></div></section>
  <PageCta title="Let’s build the next chapter together." copy="Explore what Anchal India can bring to your market."/>
 </>;
}
