import Image from "next/image"; import Link from "next/link";
import { BrandRail, PartFinder, RfqBanner, SectionHeading, WorldReach } from "@/components/site"; import { partnerBrands } from "@/data/catalog";
const sectors=[["Textiles","Fibre, yarn, fabrics and selected made-ups."],["Electrical Appliances","Selected kitchen, home and electrical appliances."],["Natural Stone & Surfaces","Tiles, granite, marble and architectural surfaces."],["Healthcare & Pharmaceuticals","Selected medicines, consumables and healthcare supplies."],["Solar & Energy Solutions","Solar panels, batteries, inverters and kits."]];
export default function Home(){return <>
<section className="hero hero-visual"><Image className="hero-image hero-motion" src="/automotive-ecosystem-v3.png" alt="Automotive components and mobility" fill priority sizes="100vw"/><div className="hero-shade"/><div className="container hero-inner"><div className="hero-copy"><p className="eyebrow"><span/>Global automotive solutions · Since 2006</p><h1>Your one trusted partner <em>for complete automotive solutions.</em></h1><p className="hero-lead">Our own brands, deep application expertise and a trusted automotive network—delivering complete solutions from India to businesses worldwide.</p><div className="hero-actions"><Link className="button button-primary" href="/products">Explore solutions →</Link><Link className="button button-ghost" href="/contact">Start a conversation</Link></div></div></div><div className="hero-caption"><b>FROM INDIA.</b><span>BUILT FOR THE WORLD.</span></div></section>
<section className="section story-v3"><div className="container story-v3-grid"><div className="story-visual kinetic-parts"><Image src="/automotive-product-universe.png" alt="Automotive systems visual" fill sizes="55vw"/><span>THE COMPLETE VEHICLE</span></div><div><p className="eyebrow"><span/>Who we are</p><h2>More than parts.<br/>Complete automotive solutions.</h2><p>Since 2006, Anchal India has built an automotive ecosystem combining our own brands, application expertise, trusted industry relationships and global supply capabilities.</p><div className="story-links"><Link href="/about"><b>Our Journey</b><span>How Anchal evolved →</span></Link><Link href="/products"><b>Our Capability</b><span>Explore vehicle systems →</span></Link><Link href="/global-presence"><b>Our Reach</b><span>India to world markets →</span></Link></div></div></div></section>
<section className="section owned-v3"><div className="container"><SectionHeading dark eyebrow="Our brands" title="Built around the aftermarket. Engineered around real demand." copy="AILYN and HARKES are Anchal India’s own brands, developed around application coverage, dependable quality and long-term customer confidence."/><div className="owned-brand-pair"><Link href="/brand-network#ailyn"><div className="brand-card-media alyn"><span className="own-logo">AILYN<small>Think Quality. Think Ailyn.</small></span></div><b>Discover AILYN →</b></Link><Link href="/brand-network#harkes"><div className="brand-card-media harkes"><span className="own-logo">HARKES<small>Automotive Solutions</small></span></div><b>Discover HARKES →</b></Link></div></div></section>
<section className="network-glimpse"><div className="container"><p>Selected names within our automotive network</p><BrandRail brands={partnerBrands}/><Link href="/brand-network">Explore brands & network →</Link></div></section>
<section className="section finder-section"><div className="container"><SectionHeading dark eyebrow="Application intelligence" title="Start with the vehicle. Find the system." copy="Choose a vehicle, model and product group—or begin with an OEM/reference code."/><PartFinder/></div></section>
<section className="section global-v3"><div className="container global-v3-grid"><div><p className="eyebrow"><span/>Global reach</p><h2>One supply network.<br/>Multiple markets.</h2><p>From one point of coordination in India, we connect automotive requirements with products, applications and supply capabilities for international markets. Deep experience across Latin America is supported by connections across Turkey, the Middle East, Egypt and the Philippines.</p><Link className="button button-light" href="/global-presence">Explore global presence →</Link></div><WorldReach/></div></section>
<section className="section beyond-v3"><div className="container"><SectionHeading eyebrow="Beyond automotive" title="Broader capabilities. Deliberately selective." copy="Our international network also supports carefully selected opportunities beyond mobility."/><div className="beyond-media-grid five">{sectors.map(([x,copy],i)=><Link href={`/beyond-automotive?sector=${i}`} className={`sector-${i+1}`} key={x}><Image src="/beyond-industries-v3.png" alt="" fill sizes="25vw"/><span><b>{x}</b><small>{copy}</small></span><em>Explore →</em></Link>)}</div></div></section><RfqBanner/>
</>}
