import Image from "next/image";
import Link from "next/link";
import { BrandRail, PartFinder, RfqBanner, SectionHeading, WorldReach } from "@/components/site";
import { markets, partnerBrands } from "@/data/catalog";
export default function Home(){return <>
 <section className="hero hero-visual"><Image className="hero-image" src="/automotive-ecosystem-v3.png" alt="" fill priority sizes="100vw"/><div className="hero-shade"/><div className="container hero-inner"><div className="hero-copy"><p className="eyebrow"><span/>Global automotive solutions · Since 2006</p><h1>Your one trusted partner <em>for complete automotive solutions.</em></h1><p className="hero-lead">Own brands, application intelligence and a trusted automotive network—coordinated from India for businesses across the world.</p><div className="hero-actions"><Link className="button button-primary" href="/products">Explore solutions →</Link><Link className="button button-ghost" href="/contact">Start an RFQ</Link></div></div></div><div className="hero-caption"><b>INDIA’S AUTOMOTIVE STRENGTH.</b><span>CONNECTED TO THE WORLD.</span></div></section>
 <section className="section story-v3"><div className="container story-v3-grid"><div className="story-visual"><Image src="/automotive-ecosystem-v3.png" alt="Conceptual automotive component ecosystem" fill sizes="55vw"/><span>Automotive is our flagship expertise</span></div><div><p className="eyebrow"><span/>Who we are</p><h2>Not a catalogue.<br/>A complete solution layer.</h2><p>Since 2006, Anchal India has grown from focused motorcycle spare-parts supply into an international automotive solutions organization built on application knowledge, own brands and long-term relationships.</p><div className="story-links"><Link href="/about"><b>Our journey</b><span>How Anchal evolved →</span></Link><Link href="/products"><b>Our capability</b><span>Explore vehicle systems →</span></Link><Link href="/global-presence"><b>Our reach</b><span>India to world markets →</span></Link></div></div></div></section>
 <section className="section owned-v3"><div className="container"><SectionHeading dark eyebrow="Brands we own" title="Two flagship brands. Equal commitment." copy="AILYN and HARKES stand side by side—supported by the same focus on application relevance, dependable presentation and customer confidence."/><div className="owned-brand-pair"><Link href="/brands#ailyn"><div className="brand-wordmark">AILYN<small>OFFICIAL LOGO SLOT</small></div><p>Explore products, applications and future packaging media.</p><span>Enter AILYN →</span></Link><Link href="/brands#harkes"><div className="brand-wordmark">HARKES<small>OFFICIAL LOGO SLOT</small></div><p>Explore products, applications and future packaging media.</p><span>Enter HARKES →</span></Link></div><p className="asset-note">Official logo and packaging assets can replace these clearly marked slots without changing the layout.</p></div></section>
 <section className="network-glimpse"><div className="container"><p>Selected names within our automotive network</p><BrandRail brands={partnerBrands}/><Link href="/brand-network">Explore brand network →</Link></div></section>
 <section className="section finder-section"><div className="container"><SectionHeading dark eyebrow="Application intelligence" title="Start with the vehicle. Find the system." copy="Choose a vehicle, model and product group—or request the matching model catalog."/><PartFinder/></div></section>
 <section className="section global-v3"><div className="container global-v3-grid"><div><p className="eyebrow"><span/>Global reach · 60%</p><h2>From India.<br/>Built for the world.</h2><p>Our identity is global. India is the origin of the network; multiple world regions are the destination. Latin America is our deepest established international market, not our only ambition.</p><Link className="button button-light" href="/global-presence">Explore global presence →</Link></div><WorldReach/></div></section>
 <section className="section latam-v3"><div className="container"><div className="latam-orbit"><span>LATIN<br/>AMERICA</span><i/><i/><i/></div><div><p className="eyebrow"><span/>Deep-rooted market strength · 40%</p><h2>Regional knowledge that moves beyond a country list.</h2><p>Years of work across Latin America have shaped our understanding of vehicle populations, regional model names, component demand and distributor expectations.</p><div className="flag-cloud">{markets.map((m,i)=><span key={m}><b>{["🇨🇴","🇬🇹","🇭🇳","🇵🇪","🇪🇨","🇨🇱","🇩🇴","🇲🇽","🇦🇷","🇺🇾","🇧🇴","🇳🇮","🇭🇹"][i]}</b>{m}</span>)}</div></div></div></section>
 <section className="section beyond-v3"><div className="container"><SectionHeading eyebrow="Beyond automotive · 10%" title="Broader capabilities. Deliberately selective."/><div className="beyond-media-grid">{["Textiles","Home Appliances","Tiles, Granite & Marble","Medicare & Healthcare"].map((x,i)=><Link href="/beyond-automotive" className={`sector-${i+1}`} key={x}><Image src="/beyond-industries-v3.png" alt="" fill sizes="25vw"/><span>{x}</span><b>Explore →</b></Link>)}</div></div></section><RfqBanner/>
 </>}
