"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { productGroups, vehicles, type VehicleType } from "@/data/catalog";

export const brandDomains:Record<string,string>={Gabriel:"gabrielindia.com",UCAL:"ucal.com",Pricol:"pricol.com",Champion:"federalmogul.com",Goetze:"federalmogul.com",Suprajit:"suprajit.com",Flash:"flashgroup.in","Uno Minda":"unominda.com","Spark Minda":"sparkminda.com",MK:"mkautoindia.com",Makino:"makino.in","Hero Rockman":"rockman.in",IFB:"ifbappliances.com",Varroc:"varroc.com",INEL:"inelindia.com"};
export function SectionHeading({eyebrow,title,copy,dark=false}:{eyebrow:string;title:string;copy?:string;dark?:boolean}){return <div className={`section-heading ${dark?"dark":""}`}><p className="eyebrow"><span/>{eyebrow}</p><h2>{title}</h2>{copy&&<p className="section-copy">{copy}</p>}</div>}
export function BrandRail({brands}:{brands:string[]}){return <div className="brand-marquee"><div>{[...brands,...brands].map((b,i)=><span className="brand-logo" key={`${b}-${i}`}><img src={`https://logo.clearbit.com/${brandDomains[b]}?size=120`} alt={`${b} logo`}/></span>)}</div></div>}

const details:Record<string,{parts:string;why:string}>={
 Engine:{parts:"Pistons, rings, cylinders, valves, gaskets, bearings and lubrication components.",why:"Converts combustion into dependable motion and demands precise application matching."},
 Transmission:{parts:"Clutch plates, hubs, gears, chains, sprockets and shifting components.",why:"Transfers engine power smoothly through the driveline."},
 "Electrical & Electronics":{parts:"Ignition, CDI/ECU, coils, regulators, sensors, switches, lighting and instrumentation.",why:"Controls starting, charging, safety and everyday reliability."},
 "Suspension & Steering":{parts:"Shock absorbers, fork parts, bushes, cone sets and steering components.",why:"Keeps the vehicle stable, controllable and comfortable."},
 Braking:{parts:"Brake shoes, pads, discs, drums, cables and control components.",why:"A safety-critical system where fitment and consistency matter."},
 "Fuel & Intake":{parts:"Carburetion, pumps, throttle bodies, valves, filters and intake components.",why:"Meters clean fuel and air for efficient performance."},
 "Controls & Cables":{parts:"Control cables, levers, throttles, switches and related hardware.",why:"Turns rider input into accurate mechanical and electrical action."},
 Wheels:{parts:"Rims, hubs, bearings and wheel-related service components.",why:"Carries load while supporting safe, efficient movement."},
 "Body & Frame":{parts:"Panels, rubber parts, mirrors, locks, stands and structural service parts.",why:"Protects the vehicle and supports function, fit and finish."},
 "Filters & Consumables":{parts:"Oil, air and fuel filters plus service and maintenance items.",why:"Protects critical systems and supports longer service life."}
};
export function GlassModal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){useEffect(()=>{const k=(e:KeyboardEvent)=>e.key==="Escape"&&onClose();addEventListener("keydown",k);return()=>removeEventListener("keydown",k)},[onClose]);return <div className="modal-backdrop" onMouseDown={onClose}><section className="detail-modal liquid-glass" role="dialog" aria-modal="true" aria-label={title} onMouseDown={e=>e.stopPropagation()}><button onClick={onClose} aria-label="Close">×</button>{children}</section></div>}
export function ProductCoverage(){const [active,setActive]=useState<string|null>(null);return <><div className="vehicle-explorer" id="systems"><div className="vehicle-stage"><div className="vehicle-shape"><span>🏍️</span><i/><i/></div>{productGroups.map((g,i)=><button className={`hotspot hotspot-${i+1}`} onClick={()=>setActive(g)} key={g}><b>+</b><span>{g}</span></button>)}</div><div className="explorer-copy"><small>MOTORCYCLE / 3-WHEELER</small><h3>Explore the complete vehicle.</h3><p>Select a hotspot to understand the system, its typical components and its role in the vehicle.</p></div></div>{active&&<GlassModal title={active} onClose={()=>setActive(null)}><small>VEHICLE SYSTEM</small><h2>{active}</h2><div className="modal-product-visual">⚙</div><p className="modal-lead">{details[active].parts}</p><div><b>What it does</b><p>{details[active].why}</p></div><Link href={`/contact?group=${encodeURIComponent(active)}`} className="button button-primary">Add to requirement →</Link></GlassModal>}</>}

export function SupplyFlow(){return <div className="cinematic-flow">{["Requirement received","Application identified","Solution matched","Quality & consolidation","Documentation","Global delivery"].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><i>{["▤","⌖","⚙","▣","▧","◉"][i]}</i><b>{x}</b></div>)}</div>}
export function WorldReach(){return <div className="world-reach" aria-label="Animated map showing connections from India to world markets"><div className="globe-lines"/><div className="continent c-americas"/><div className="continent c-europe"/><div className="continent c-africa"/><div className="continent c-asia"/><span className="india-node">INDIA<i/></span>{["Latin America","Turkey","Middle East","Egypt","Philippines"].map((x,i)=><span className={`reach-label reach-${i+1}`} key={x}>{x}</span>)}{[1,2,3,4,5].map(i=><i className={`reach-route reach-route-${i}`} key={i}><b>▰</b></i>)}<span className="china-node">CHINA · SUPPLY NETWORK</span></div>}

const sampleParts:Record<string,{name:string;code:string}[]>={Engine:[{name:"Piston Kit",code:"OEM reference verified on enquiry"},{name:"Piston Ring Set",code:"Cross-reference available"},{name:"Cylinder & Gasket Set",code:"Application-specific"}],Transmission:[{name:"Clutch Plate Set",code:"OEM reference verified on enquiry"},{name:"Chain & Sprocket Kit",code:"Application-specific"}]};
export function PartFinder(){const [type,setType]=useState<VehicleType>("Motorcycle"),[brand,setBrand]=useState(""),[model,setModel]=useState(""),[group,setGroup]=useState(""),[results,setResults]=useState(false),[code,setCode]=useState("");const brands=useMemo(()=>Array.from(new Set(vehicles.filter(v=>v.type===type).map(v=>v.brand))),[type]);const models=vehicles.filter(v=>v.type===type&&(!brand||v.brand===brand));const selected=vehicles.find(v=>v.id===model);function changeType(v:VehicleType){setType(v);setBrand("");setModel("");setGroup("");setResults(false)}return <><div className="finder liquid-glass"><div className="type-toggle"><button className={type==="Motorcycle"?"active":""} onClick={()=>changeType("Motorcycle")}>Motorcycle</button><button className={type==="3-Wheeler"?"active":""} onClick={()=>changeType("3-Wheeler")}>3-Wheeler</button></div><div className="finder-fields"><label><span>Brand</span><select value={brand} onChange={e=>{setBrand(e.target.value);setModel("")}}><option value="">Select brand</option>{brands.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Model</span><select value={model} onChange={e=>setModel(e.target.value)} disabled={!brand}><option value="">Select model</option>{models.map(x=><option key={x.id} value={x.id}>{x.model}</option>)}</select></label><label><span>Product group</span><select value={group} onChange={e=>setGroup(e.target.value)} disabled={!model}><option value="">Select group</option>{productGroups.map(x=><option key={x}>{x}</option>)}</select></label><button className="button button-primary finder-button" disabled={!group} onClick={()=>setResults(true)}>Find parts →</button></div>{selected&&<div className="catalog-action"><div><b>{selected.brand} {selected.model}</b><span>Model-specific catalogue support</span></div><Link href={`/contact?vehicle=${model}&request=catalog`}>Request catalogue →</Link></div>}<div className="code-search"><div><small>KNOW THE CODE?</small><b>Find a part by OEM / reference code</b></div><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Enter OEM, supplier or part code"/><Link href={`/contact?code=${encodeURIComponent(code)}`}>Search →</Link></div></div>{results&&<GlassModal title={`${selected?.brand} ${selected?.model}`} onClose={()=>setResults(false)}><small>APPLICATION INTELLIGENCE</small><h2>{selected?.brand} {selected?.model}</h2><p className="modal-lead">{group}</p><div className="part-results">{(sampleParts[group]||[{name:`${group} components`,code:"Verified against the source catalogue before quotation"}]).map(p=><article key={p.name}><div>⚙</div><b>{p.name}</b><span>{p.code}</span></article>)}</div><Link className="button button-primary" href={`/contact?vehicle=${model}&group=${encodeURIComponent(group)}`}>Request verified references →</Link></GlassModal>}</>}

export function ContactForm(){const [sent,setSent]=useState(false),[kind,setKind]=useState("Vehicle / Model Parts");function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSent(true)}if(sent)return <div className="form-success"><b>Thank you.</b><p>Your enquiry has been captured. For immediate assistance, use the communication dock.</p></div>;return <form className="contact-form smart-rfq" onSubmit={submit}><div className="rfq-kinds">{["Vehicle / Model Parts","OEM / Part Number","Requirement List","AILYN / HARKES","Beyond Automotive","General Enquiry"].map(x=><button type="button" className={kind===x?"active":""} onClick={()=>setKind(x)} key={x}>{x}</button>)}</div><div className="form-grid"><label>Name *<input required/></label><label>Company *<input required/></label><label>Email *<input required type="email"/></label><label>Country *<input required/></label><label>Phone / WhatsApp<input/></label><label>Requirement type<input readOnly value={kind}/></label></div>{kind==="OEM / Part Number"&&<label>OEM / reference code<input placeholder="Enter the code exactly as available"/></label>}<label>Requirement details<textarea required rows={5} placeholder="Vehicle, model, product, quantity or market requirement…"/></label><label className="upload-zone">Attach Excel, CSV, PDF or images<input type="file" multiple accept=".xlsx,.xls,.csv,.pdf,image/*"/></label><button className="button button-primary">Submit enquiry →</button></form>}
export function RfqBanner({context="Home"}:{context?:string}){const copy=context==="Products"?["KNOW THE VEHICLE. KNOW THE CODE.","Or just know the requirement."]:context==="About"?["LET’S BUILD THE NEXT CHAPTER.","Start with a conversation."]:["TELL US WHAT YOUR MARKET NEEDS.","We will help map the right solution."];return <section className="rfq-banner"><div className="container"><p>{copy[0]}</p><h2>{copy[1]}</h2><Link className="button button-light" href="/contact">Start a conversation →</Link></div></section>}
